name: ipytablewidgets

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.9
  - nodejs
  - pkgconfig
  - pip
  - numpy>=1.16.5
  - pandas>=1.0.0
  - jupyterlab=2
  - pip:
      - -e .
