name: End to End Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.8", "3.9", "3.10", "3.11"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge, anaconda
    - name: Create the conda environment
      run: |
        conda env create -q python=${{ matrix.python_version }} -f environment.yml
    - name: Run tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate ipytablewidgets
        python -m pip install jupyterlab==3.6.1 # required 4 galata
        conda install yarn
        cd ui-tests/	
        yarn
        yarn run start-jlab:detached
        yarn run test
      - name: Upload output file
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cell-artifact
          path: ui-tests/test-output/test/screenshots/end2end_cell_*.png
